- name: Pull docker image of Calculator
  hosts: all
  tasks:
    - name: Install pip requests library
      pip:
        name: requests
        state: present
    - name: Pull image
      docker_image:
        name: shivanshsethi2000/spe_mini_proj:latest
        source: pull
    - name: creating updated container
      shell: docker run -id shivanshsethi2000/spe_mini_proj:latest